language: python
python:
   - 2.7
   - 3.2
   - 3.3
   - 3.4
   - 3.5
   - pypy
   - pypy3

install:
   - "pip install ."
   - "pip install -r requirements/test.txt"
   
script: "nosetests"

notifications:
   email: false
